---
- name: Install Checkmk
  ansible.builtin.apt:
    deb: "{{ downloadlink }}"
  when: ansible_os_family == "Debian"

- name: Ensure Checkmk service is enabled
  ansible.builtin.systemd:
    name: apache2
    enabled: true
    state: started