---
- name: "Install Checkmk and create Sites."
  ansible.builtin.import_role:
    name: checkmk.general.server

- name: "Activate Changes on all Sites."
  checkmk.general.activation:
    server_url: "{{ checkmk_var_server_url }}"
    site: "{{ checkmk_var_site }}"
    automation_user: "cmkadmin"
    automation_secret: "{{ checkmk_server_admin_pass }}"