---
- name: Install package based on OS type
  hosts: all
  become: yes

  vars:
    deb_package: "./packages/check-mk-agent.deb"
    rpm_package: "./packages/check-mk-agent.rpm"

  tasks:
    - name: Check OS Family
      ansible.builtin.setup:
      register: system_info

    - name: Install .deb package on Debian-based systems
      ansible.builtin.copy:
        src: "{{ deb_package }}"
        dest: /tmp/your_package.deb
      when: system_info.ansible_facts['ansible_os_family'] == 'Debian'

    - name: Install .deb package
      ansible.builtin.apt:
        deb: /tmp/your_package.deb
      when: system_info.ansible_facts['ansible_os_family'] == 'Debian'

    - name: Install .rpm package on RedHat-based systems
      ansible.builtin.copy:
        src: "{{ rpm_package }}"
        dest: /tmp/your_package.rpm
      when: system_info.ansible_facts['ansible_os_family'] == 'RedHat'

    - name: Install .rpm package
      ansible.builtin.yum:
        name: /tmp/your_package.rpm
        state: present
      when: system_info.ansible_facts['ansible_os_family'] == 'RedHat'