---
- name: Verify Checkmk SHA256 checksum
  shell: "sha256sum /tmp/check-mk-raw-2.3.0p27_0.noble_amd64.deb | awk '{print $1}'"
  register: checksum_result
  changed_when: false

- name: Fail if checksum does not match
  fail:
    msg: "Checksum verification failed!"
  when: checksum_result.stdout != "94a484c17e862d7ca02996064477a9f7a1c15008ba234906e0afb4081e91968a"
