---
- name: Create Checkmk instance
  ansible.builtin.command: omd create monitoring
  args:
    creates: "/omd/sites/monitoring"
  register: omd_create

- name: Start Checkmk instance
  ansible.builtin.command: omd start monitoring

- name: Save API-Key
  ansible.builtin.command: cat /opt/omd/sites/monitoring/var/check_mk/web/automation/automation.secret
  register: checkmk_api_secret