---
- name: Create Checkmk instance
  ansible.builtin.command: omd create monitoring
  args:
    creates: "/omd/sites/monitoring"
  register: omd_create

- name: Start Checkmk instance
  ansible.builtin.command: omd start monitoring

- name: Set API-Secret
  ansible.builtin.command: echo "{{ automation_secret }}" > /opt/omd/sites/monitoring/var/check_mk/web/automation/automation.secret
  