---
- name: Create Checkmk instance
  ansible.builtin.command: omd create monitoring
  args:
    creates: "/omd/sites/monitoring"
  register: omd_create

- name: Start Checkmk instance
  ansible.builtin.command: omd start monitoring
  ignore_errors: true

#- name: Set API-Secret
#  ansible.builtin.command: echo "{{ automation_secret }}" > /opt/omd/sites/monitoring/var/check_mk/web/automation/automation.secret

- name: Extract Checkmk automation secret
  ansible.builtin.command: cat /omd/sites/monitoring/var/check_mk/web/automation/automation.secret
  register: checkmk_api_secret

- name: Store automation secret as a fact
  ansible.builtin.set_fact:
    checkmk_automation_secret: "{{ checkmk_api_secret.stdout }}"

#- name: Output
#  ansible.builtin.debug:
#    msg: "{{ checkmk_api_secret }}"