---
- name: Add hosts to Checkmk
  checkmk.general.host:
    server_url: "http://192.168.1.245"
    site: monitoring
    automation_user: "automation"
    automation_secret: "{{ checkmk_api_secret.stdout }}"
    name: "cmkserver"
    attributes:
      alias: "Checkmk-Server"
      ipaddress: "192.168.1.245"
#      description: "{{ item.description }}"
    folder: "/"
    state: present
  #loop:
  #  - { name: "server", ipaddress: "192.168.1.245"}
   # - { hostname: "server2", ip: "192.168.1.11", description: "DB-Server" }
   # - { hostname: "server3", ip: "192.168.1.12", description: "Proxy-Server" }

- name: "Start activation on all sites."
  checkmk.general.activation:
      server_url: "http://192.168.1.245"
      site: monitoring
      automation_user: "automation"
      automation_secret: "{{ checkmk_api_secret.stdout }}"
  run_once: 'true'