---
- name: Add hosts to Checkmk
  checkmk.general.host:
    server_url: "http://192.168.1.245"
    site: monitoring
    automation_user: "automation"
    automation_secret: "{{ checkmk_api_secret.stdout }}"
    name: "{{ item.hostname }}"
    atributes:
      ipaddress: "{{ item.ip }}"
#      description: "{{ item.description }}"
    state: present
  loop:
    - { hostname: "server", ip: "192.168.1.245"}
   # - { hostname: "server2", ip: "192.168.1.11", description: "DB-Server" }
   # - { hostname: "server3", ip: "192.168.1.12", description: "Proxy-Server" }
