---
- name: Patch Linux Systeme (Debian + RedHat)
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: debian
      when: ansible_os_family == "Debian"
    - role: redhat
      when: ansible_os_family == "RedHat"
