---
- name: Install Checkmk with Verification
  hosts: localhost
  connection: local
  become: yes
#  vars_files:
#    - ./patchmgmt/checkmk/group_vars/site.yml
  roles:
    #- 01_checkmk_download
    #- 02_checkmk_verify
    #- 03_checkmk_install
    #    - 04_checkmk_create_instance
    #- 05_checkmk_config
    #
    #TODO
    #install requs:
    #sudo apt install python3-pip
    #ansible-galaxy collection install checkmk.general
    #
    #- 10_install_requirements
    #- 11_install_collection_checkmk.general
    #- 12_install_checkmk
    - 13_create_site
    - 14_set_webui_admin
    - 15_add_basic_clients
