---
- name: Install Checkmk with Verification
  hosts: localhost
  remote: local
  become: yes
  roles:
    - 01_checkmk_download
    - 02_checkmk_verify
    - 03_checkmk_install
    #    - 04_checkmk_create_instance
    - 05_checkmk_config
