---
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "{{ checkmk_server_url }}"
    site: "{{ site_name }}"
    automation_user: "automation"
    automation_secret: "{{ checkmk_api_secret.stdout }}"
    auth_type: "password"
    name: "cmkadmin"
    password: "{{ cmkadmin_password }}"
#    roles: ["admin"]
    state: reset_password
#  no_log: true
