---
- name: Set Checkmk admin password
  checkmk.general.activation:
    server_url: "192.168.1.245"
    site: "monitoring"
    automation_user: "cmkadmin"
    automation_secret: "{{ cmkadmin_password }}"
        #  ansible.builtin.command: echo "{{ cmkadmin_password }}" | omd setpassword monitoring cmkadmin
  #no_log: true
#- name: "Activate Changes on all Sites."