---
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "192.168.1.245"
    site: "monitoring"
    automation_user: "automation"
    automation_secret: "W5gevgvyOk4XGHZFuUzfGIL5user@"  # Use extracted secret
    name: "cmkadmin"
    password: "Start123$"
    roles: ["admin"]
    state: present
  no_log: true  # Hide sensitive data from logs
