---
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "http://192.168.1.245"
    site: "monitoring"
    automation_user: "automation"
    automation_secret: "W5gevgvyOk4XGHZFuUzfGIL5"
    name: "admincmk"
    password: "Start123$"
    roles: ["admin"]
    state: present
#  no_log: true
