---
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "http://192.168.1.245"
    site: "monitoring"
    automation_user: "automation"
    automation_secret: "{{ automation_secret }}"
    auth_type: "password"
    name: "cmkadmin"
    password: "{{ cmkadmin_password }}"
#    roles: ["admin"]
    state: reset_password
#  no_log: true
