---
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "http://192.168.1.245"
    site: "monitoring"
    automation_user: "automation"
    automation_secret: "W5gevgvyOk4XGHZFuUzfGIL5"
    auth_type: "password"
    name: "cmkadmin"
    password: "Start123456789$"
#    roles: ["admin"]
    state: present
#  no_log: true
