---
- name: Extract Checkmk automation secret
  ansible.builtin.command: cat /omd/sites/monitoring/var/check_mk/web/automation/automation.secret
  register: checkmk_api_secret
  changed_when: false
  
- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "{{ checkmk_server_url }}"
    site: "monitoring"
    automation_user: "{{ checkmk_automation_user }}"
    automation_secret: "{{ checkmk_automation_secret }}"
    name: "cmkadmin"
    password: "{{ cmkadmin_password }}"
    roles: ["admin"]
    state: present
