---
- name: Set Checkmk admin password
  vars_files:
    - ./patchmgmt/checkmk/group_vars
  ansible.builtin.command: echo "{{ cmkadmin_password }}" | omd setpassword monitoring cmkadmin
  no_log: true
