---
- name: Extract Checkmk automation secret
  ansible.builtin.command: cat /omd/sites/monitoring/var/check_mk/web/automation/automation.secret
  register: checkmk_api_secret
  changed_when: false
  no_log: true  # Hide secret from logs for security

- name: Set Checkmk admin password
  checkmk.general.user:
    server_url: "{{ checkmk_server_url }}"
    site: "monitoring"
    automation_user: "automation"
    automation_secret: "{{ checkmk_api_secret.stdout }}"  # Use extracted secret
    name: "cmkadmin"
    password: "{{ cmkadmin_password }}"
    roles: ["admin"]
    state: present
  no_log: true  # Hide sensitive data from logs
