---
- name: Install Checkmk package
  apt:
    deb: "/tmp/check-mk-raw-2.3.0p27_0.noble_amd64.deb"
    state: present

- name: Verify Checkmk installation
  command: "omd version"
  register: omd_version
  changed_when: false

- name: Display installed Checkmk version
  debug:
    msg: "Installed Checkmk version: {{ omd_version.stdout }}"
