- name: Ensure Checkmk site is running
  ansible.builtin.command: omd start monitoring
  changed_when: false

- name: Copy Checkmk configuration script
  ansible.builtin.copy:
    src: files/checkmk-config.sh
    dest: /tmp/checkmk-config.sh
    mode: "0755"

- name: Execute Checkmk configuration
  ansible.builtin.command: bash /tmp/checkmk-config.sh
  register: checkmk_config_output
  changed_when: "'configured' in checkmk_config_output.stdout"

- name: Show configuration output
  ansible.builtin.debug:
    msg: "{{ checkmk_config_output.stdout }}"
